Add /calendar/:username route to get user calendar data
Real-Dev-Squad/calendar-API pull request #47
Opened 2022-12-09 20:52 UTC by prakashchoudhary07

2022-12-09 20:53 UTC, prakashchoudhary07 commented on controllers/calendar.ts
> +  return res.json({ data: userCalenders });
Do we return `isDeleted` field or not

2022-12-10 03:31 UTC, ankurnarkhede requested changes

2022-12-10 03:31 UTC, ankurnarkhede commented on controllers/calendar.ts
> +    const { username } = req.params;
Validate if req.params.username === req.userdata.username

2022-12-13 04:01 UTC, ankurnarkhede requested changes

2022-12-15 02:55 UTC, ankurnarkhede approved these changes

2022-12-15 02:55 UTC, merged