Create event api
Real-Dev-Squad/calendar-API pull request #49
Opened 2022-12-10 07:29 UTC by prakashchoudhary07

2022-12-13 04:14 UTC, ankurnarkhede requested changes

2022-12-13 04:14 UTC, ankurnarkhede commented on controllers/events.ts
> +    console.log(event);
Add log to identify the specific log.

2022-12-21 03:55 UTC, prakashchoudhary07 commented
In Doc, we are passing calendarId for POST data, but we have no field to store calendarId in parentEvent or childEvent.
I belive we will be adding that in parentEvent right? Correct me if I am missing some thing here

@ankurnarkhede

2022-12-21 10:09 UTC, ankurnarkhede commented
> In Doc, we are passing calendarId for POST data, but we have no field to store calendarId in parentEvent or childEvent. I belive we will be adding that in parentEvent right? Correct me if I am missing some thing here
> 
> @ankurnarkhede

We need to add it in parentEvent schema. Its already added here: https://github.com/Real-Dev-Squad/calendar-API/blob/512d797cbb065ad06bf6123b41859b1eacaef48d/prisma/schema.prisma#L65-L66

2022-12-22 04:05 UTC, prakashchoudhary07 commented
> 

Will we be storing calendarId in eventTypeId?

2022-12-22 04:08 UTC, ankurnarkhede commented
> > 
> 
> Will we be storing calendarId in eventTypeId?

No, eventTypeId will be the FK from EventType table. It has nothing to do with calendarId.

2022-12-24 14:14 UTC, ankurnarkhede requested changes
Still reviewing, will add the full review in sometime.

2022-12-24 14:14 UTC, ankurnarkhede commented on constants/recurringFrequency.ts
> +export const RECURRING_FREQUENCY: any = {
Lets add all config to config object itself.

2022-12-24 14:14 UTC, ankurnarkhede commented on controllers/events.ts
> +import { formateParentEvent } from "../utils/formate-response";
format*

2022-12-28 03:48 UTC, harshith-venkatesh commented
* Recurring logic is currently applied for daily frequency

2023-03-03 13:30 UTC, iRohitGaur commented on controllers/events.ts
> +    // Get attnedee ids from email
`attnedee` --> `attendee`

2023-03-03 13:31 UTC, iRohitGaur commented on routes/events.ts
> +// eslint-disable-next-line @typescript-eslint/no-misused-promises
why disable?

2023-03-03 13:31 UTC, iRohitGaur commented on routes/events.ts
> +router.post("/", authenticate, validate(postEventSchema), postEvent);
why disable?

2023-03-03 13:32 UTC, iRohitGaur commented on services/eventsService.ts
> +// const handelDailyEventsTimeUpdate = () => {};
suggestion: should be removed if not required.

2023-03-05 17:31 UTC, DeRaowl approved these changes

2023-03-13 13:00 UTC, merged