Fix/authorization
Real-Dev-Squad/calendar-API pull request #98
Opened 2023-07-27 22:58 UTC by prakashchoudhary07

Add middleware to restrict users from accessing other users calendar, events, editing other events

2023-07-28 15:00 UTC, isVivek99 approved these changes

2023-07-28 15:01 UTC, isVivek99 commented
tests are failing

2023-07-28 16:40 UTC, iRohitGaur requested changes
tests are failing

2023-07-29 01:49 UTC, prakashchoudhary07 commented
Fixed it

2023-07-29 01:56 UTC, iRohitGaur approved these changes

2023-07-29 04:42 UTC, isVivek99 approved these changes

2023-07-29 05:09 UTC, harshith-venkatesh approved these changes

2023-07-29 05:10 UTC, merged